imports = ["/etc/containerd/conf.d/*.toml"]
oom_score = 0
version = 3

[grpc]
  max_recv_message_size = 16777216
  max_send_message_size = 16777216

[plugins."io.containerd.cri.v1.images".pinned_images]
  sandbox = "{pause_image}"

[plugins."io.containerd.cri.v1.images".registry]
  config_path = "/etc/containerd/hosts.d"

# The CRI puller is only used when use_local_image_pull=true.
# we need to set the hosts when the hosts are pulled using transfer paths.
[plugins."io.containerd.transfer.v1.local"]
  config_path = "/etc/containerd/hosts.d"

[plugins."io.containerd.cri.v1.runtime".containerd]
  default_runtime_name = "runc"

[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runc.options]
  SystemdCgroup = true

