name: Lint

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'components/**'
      - '.github/workflows/lint.yml'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'components/**'
      - '.github/workflows/lint.yml'
      - 'pyproject.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write         # for reviewdog to report results on PRs
  pull-requests: write  # so reviewdog can leave comments on PRs

jobs:
  call-inclusive-naming-check:
    name: Inclusive Naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@965ea21624a58f27460725561603914b422d693e # main
    permissions:
      contents: read
      checks: write
      pull-requests: write
    with:
      fail-on-error: "true"
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Astral UV
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.12"

      - name: Install kube-galaxy
        shell: bash
        run: |
          uv tool install tox --with tox-uv

      - name: Run lint checks
        run: |
          tox -e lint
