name: Lint

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'components/**'
      - '.github/workflows/lint.yml'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'components/**'
      - '.github/workflows/lint.yml'
      - 'pyproject.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write         # for reviewdog to report results on PRs
  pull-requests: write  # so reviewdog can leave comments on PRs

jobs:
  call-inclusive-naming-check:
    name: Inclusive Naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@7aa0f7a606f182bd03a7adb28e0d710216101ca5 # main
    permissions:
      contents: read
      checks: write
      pull-requests: write
    with:
      fail-on-error: "true"
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Astral UV
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "3.12"

      - name: Install kube-galaxy
        shell: bash
        run: |
          uv tool install tox --with tox-uv

      - name: Run lint checks
        run: |
          tox -e lint
