name: Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'components/**'
      - '.github/workflows/test.yml'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'components/**'
      - '.github/workflows/test.yml'
      - 'pyproject.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Astral UV
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: "3.12"

      - name: Install kube-galaxy
        shell: bash
        run: |
          uv tool install tox --with tox-uv

      - name: Run unit tests
        run: |
          tox -e unit
